cricket_application/urls.py
from django.urls import path

from . import views

app_name = 'cricket_application'

urlpatterns = [
    path('', views.MatchesView, name='home'),
    path('schedule_match/', views.CreateMatch, name='schedule'),
    path('teams/', views.TeamList, name='team_list'),
    path('teams/<team_identifier>/', views.TeamDetailView, name='team_detail'),
    path('player_detail/<id>/', views.PlayerDetailView, name='player_detail'),
    path('save_match/', views.save_match, name='save_match'),
    path('update_match/<id>', views.update_match, name='update_match'),
    path('points_table/', views.TeamPoints, name='teamPoints'),
    path('login/', views.loginpage, name='login'),
    path('logout', views.logoutpage, name='logout'),
]

cricket_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cricket_application.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/matches/match_create_form.html
{% extends 'base.html' %}
{% block content %}
<style>
a{color: orange}
</style>
    <div class="container">
        <div class="row">

            <div class="offset-3 col-4">
                <h4 align="center">Schedule a match</h4>
                <form action="{% url 'cricket_application:save_match' %}" method="post">
                    {% csrf_token %}
                    <label for="Teams">Match Between :</label>
                    <select name="Teams" id="Teams" class="form-control" required="True">
                        <option></option>
                        {% for teams in match_teams %}
                            <option>{{ teams }}</option>
                        {% endfor %}
                    </select>
                    {% if not match_teams %}
                        <a href="/admin/cricket_application/cricketteam/add/"> Add Teams here..</a><br>
                    {% endif %}
                    <label for="venue"> Match Venue :</label>
                    <select name="venue" id="venue" class="form-control" required="True">
                        <option></option>
                        {% for venue in venues %}
                            <option>{{ venue }}</option>
                        {% endfor %}
                    </select>
                    {% if not venues %}
                        <a href="/admin/cricket_application/matchvenues/add/"> Add Venues here..</a><br>
                    {% endif %}
                    <label for="date"> Match Date :</label>
                    <input type="datetime-local" id="date" name="match_date" class="form-control" required="True">
                    <br>
                    <center>
                        <input type="submit" value="Schedule a Match" class="btn btn-primary">
                    </center>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/matches/match_fixture.html
{% extends 'base.html' %}
{% block content %}
    <div class="container-fluid">
        <h2 align="center">Match Fixtures</h2>
        <div class="row">
            {% if matches %}
                <table class="table">
                    <thead align="center" class="bg-dark">
                    <tr>
                        <th>Match Between Teams</th>
                        <th>Match Date</th>
                        <th>Match Location</th>
                        <th>Match Winner</th>
                    </tr>
                    </thead>
                    <tbody align="center">
                    {% for match in matches %}
                        <tr>
                            <td>
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col" align="center">
                                            <img src="{{ match.playing_team1_logo.url }}" height="50" width="50">
                                            <h5>{{ match.playing_team1 }}</h5>
                                        </div>
                                        <div class="col" align="center">
                                            <h4>Vs</h4>
                                        </div>
                                        <div class="col" align="center">
                                            <img src="{{ match.playing_team2_logo.url }}" height="50" width="50">
                                            <h5>{{ match.playing_team2 }}</h5>
                                        </div>
                                    </div>
                                </div>
                            </td>
                            <td>
                                <div class="card-body">
                                    {{ match.match_date }}
                                </div>
                            </td>
                            <td>
                                <div class="card-body">
                                    {{ match.match_venue }}
                                </div>
                            </td>
                            <td>
                                <div class="card-body">
                                    {% if not match.match_winner %}
                                        <a href="/update_match/{{ match.id }}" class="btn btn-warning">Update</a>
                                    {% else %}
                                        {{ match.match_winner }}
                                    {% endif %}
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <h3>No matches scheduled..</h3>
            {% endif %}
        </div>
        {#        <a href="{% url 'cricket_application:matches_create' %}">Create another match</a>#}
    </div>

{% endblock %}

templates/matches/update_match_winner.html
{% extends 'base.html' %}
{% block content %}
    <h4 style="text-align: center">Update match winner</h4>
    <div class="container">
        <div class="row">
            <div class="offset-3 col-4">
                <form action="{% url 'cricket_application:update_match' match.id %}" method="post">
                    {% csrf_token %}
                    <label for="TeamA">Playing Team1 :</label>
                    <input name="TeamA" id="TeamA" class="form-control" readonly value="{{ match.playing_team1 }}">
                    <label for="TeamB">Playing Team2 :</label>
                    <input name="TeamB" id="TeamB" class="form-control" readonly value="{{ match.playing_team2 }}">
                    <label for="venue"> Match Venue :</label>
                    <input name="venue" id="venue" class="form-control" readonly value="{{ match.match_venue }}">
                    <label for="date"> Match Date :</label>
                    <input type="text" id="date" name="match_date" class="form-control" readonly
                           value="{{ match.match_date }}">
                    <label for="win"> Match Winner :</label>
                    <select name="win" id="win" class="form-control">
                        <option></option>
                        <option>{{ match.playing_team1 }}</option>
                        <option>{{ match.playing_team2 }}</option>
                    </select>
                    <br>
                    <center>
                        <input type="submit" value="Update Match Winner" class="btn btn-success">
                    </center>
                </form>
            </div>
        </div>
    </div>

{% endblock %}