cricket_application/urls.py
from django.urls import path

from . import views

app_name = 'cricket_application'

urlpatterns = [
    path('', views.MatchesView, name='home'),
    path('schedule_match/', views.CreateMatch, name='schedule'),
    path('teams/', views.TeamList, name='team_list'),
    path('teams/<team_identifier>/', views.TeamDetailView, name='team_detail'),
    path('player_detail/<id>/', views.PlayerDetailView, name='player_detail'),
    path('save_match/', views.save_match, name='save_match'),
    path('update_match/<id>', views.update_match, name='update_match'),
    path('points_table/', views.TeamPoints, name='teamPoints'),
    path('login/', views.loginpage, name='login'),
    path('logout', views.logoutpage, name='logout'),
]

cricket_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cricket_application.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cricket_application/models.py
from django.db import models
from django_countries.fields import CountryField


class CricketTeam(models.Model):
    '''
    CricketTeam model class is created to store Teams
    '''
    team_identifier = models.CharField(max_length=10, unique=True)
    team_name = models.CharField(max_length=100)
    team_logo = models.ImageField(upload_to='team_logo')
    club_state = models.CharField(max_length=100, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    modified_at = models.DateTimeField(auto_now=True, editable=False)

    def __str__(self):
        return self.team_name


class CricketPlayer(models.Model):
    '''
        CricketPlayer model class is created to store players
    '''
    player_id = models.IntegerField(primary_key=True)
    teams = models.ForeignKey(CricketTeam, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    player_image = models.ImageField(upload_to='players')
    jersey_number = models.PositiveIntegerField(unique=True)
    country = CountryField(multiple=False)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    modified_at = models.DateTimeField(auto_now=True, editable=False)

    def __str__(self):
        return self.first_name + ' ' + self.last_name


class PlayerHistory(models.Model):
    '''
        PlayerHistory model class is created to store player details
    '''
    player = models.OneToOneField(CricketPlayer, on_delete=models.CASCADE)
    matches_played = models.PositiveIntegerField()
    total_runs = models.PositiveIntegerField()
    highest_score = models.PositiveIntegerField()
    fifties = models.PositiveIntegerField()
    hundreds = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    modified_at = models.DateTimeField(auto_now=True, editable=False)

    def __str__(self):
        return self.player.first_name

    class Meta:
        verbose_name = "PlayerHistory"
        verbose_name_plural = "PlayerHistory"


class MatchesFixture(models.Model):
    '''
        MatchesFixture model class is created to store match schedule details
    '''
    playing_team1 = models.CharField(max_length=100)
    playing_team2 = models.CharField(max_length=100)
    playing_team1_logo = models.ImageField()
    playing_team2_logo = models.ImageField()
    match_venue = models.CharField(max_length=100)
    match_date = models.DateTimeField()
    match_winner = models.CharField(max_length=100, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    modified_at = models.DateTimeField(auto_now=True, editable=False)

    def __str__(self):
        return self.match_winner


class Points(models.Model):
    '''
        Points model class is created to store team points details
    '''
    team = models.CharField(max_length=100)
    matches_played = models.PositiveIntegerField(default=0)
    matches_won = models.PositiveIntegerField(default=0)
    matches_lost = models.PositiveIntegerField(default=0)
    matches_tied = models.PositiveIntegerField(default=0)
    points = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.team

    class Meta:
        verbose_name = 'Points'
        verbose_name_plural = 'Points'


class MatchVenues(models.Model):
    '''
        MatchVenues model class is created to store match location details
    '''
    stadium_name = models.CharField(max_length=100)
    stadium_city = models.CharField(max_length=100)

    def __str__(self):
        return self.stadium_name

    class Meta:
        verbose_name = "MatchVenues"
        verbose_name_plural = "MatchVenues"

templates/teams/team_detail.html
{% extends 'base.html' %}
{% load static %}
<html>
<head>
    {% block title %}
        <title>Players</title>
    {% endblock title %}
</head>
<body>
{% block content %}
    <style>
        body {
            background-color: aquamarine
        }

        h5 {
            color: blue
        }

        strong {
            font-size: 30px;
            color: blueviolet
        }
    </style>
    <div class="container-fluid">
        <div class="row">
            <div class="col mt-2 mb-2" align="center">
                <img src="{{ team.team_logo.url }}" width="100" height="100">
                <strong>{{ team.team_name |capfirst }} Cricket Team Players</strong>
            </div>
        </div>
        {% if team.cricketplayer_set.all %}
            <div class="row">
                {% for player in team.cricketplayer_set.all %}
                    <div class="col" align="center">
                        <div class="card-header"></div>
                        <div class="card-body bg-light"
                             style="border-radius: 5px;padding: 10px;width: 300px;height: 350px">
                            <a href="{% url 'cricket_application:player_detail' player.player_id %}">
                                <img src="{{ player.player_image.url }}" alt="Player Image" height="200" width="200">
                                <h5><a href="{% url 'cricket_application:player_detail' player.player_id %}">
                                    {{ player.first_name }} {{ player.last_name }}</a></h5>
                            </a>
                            <h5>Jersy No:{{ player.jersey_number }}</h5>
                            <h5>Country: {{ player.country.name|upper }}</h5>

                        </div>
                        <div class="card-footer"></div>
                    </div>


                {% endfor %}
            </div>
        {% else %}
            <h3>No data available</h3>
            <a href="/admin/cricket_application/cricketplayer/add/" class="btn btn-primary">Add a player</a>
        {% endif %}
    </div>
{% endblock content %}
</body>
</html>

templates/teams/team_list.html
{% extends 'base.html' %}
<html>
<head>
    {% block title %}
        <title>Teams</title>
    {% endblock title %}
</head>
<body>
{% block content %}

    <div class="container-fluid">

        <h3 align="center">List of Cricket Teams</h3>

        <div class="row mt-4">
            {% if teams %}
                {% for team in teams %}
                    <div class="col" align="center">
                        <div class="card-header"></div>
                        <div class="card-body bg-light"
                             style="border-radius: 5px;padding: 10px;width: 300px;height: 300px">
                            <a href="{{ team.team_identifier }}/">
                                <img src="{{ team.team_logo.url }}" alt={{ team.team_name }} height="200" width="200">
                                <h3><strong><a href="{{ team.team_identifier }}/">
                                    {{ team.team_name }}</a></strong></h3>
                            </a>
                        </div>
                        <div class="card-footer"></div>
                    </div>
                {% endfor %}
            {% else %}
                <h2>No Teams Created</h2><br>
                <a href="/admin/cricket_application/cricketteam/add/">
                    <button class="ml-5 btn btn-warning">Create here</button>
                </a>
            {% endif %}
        </div>
    </div>
{% endblock content %}
</body>
</html>

templates/teams/team_points.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        
        <div class="row">
            <div class="offset-3 col-6">
            <h2><a href="{% url 'cricket_application:teamPoints' %}" class="btn col btn-danger">Get Points</a></h2>
                {% if points %}
                    <table class="table table-bordered bg-dark">
                        <thead>
                        <tr>
                            <th>Team Name</th>
                            <th>Matches</th>
                            <th>Won</th>
                            <th>Lost</th>
                            <th>Tied</th>
                            <th>Points</th>
                        </tr>
                        </thead>
                        <tbody align="center">
                        {% for team in points %}
                            <tr>
                                <td>{{ team.team }}</td>
                                <td>{{ team.matches_played }}</td>
                                <td>{{ team.matches_won }}</td>
                                <td>{{ team.matches_lost }}</td>
                                <td>{{ team.matches_tied }}</td>
                                <td>{{ team.points }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <h3>No data available</h3>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}