cricket_application/urls.py
from django.urls import path

from . import views

app_name = 'cricket_application'

urlpatterns = [
    path('', views.MatchesView, name='home'),
    path('schedule_match/', views.CreateMatch, name='schedule'),
    path('teams/', views.TeamList, name='team_list'),
    path('teams/<team_identifier>/', views.TeamDetailView, name='team_detail'),
    path('player_detail/<id>/', views.PlayerDetailView, name='player_detail'),
    path('save_match/', views.save_match, name='save_match'),
    path('update_match/<id>', views.update_match, name='update_match'),
    path('points_table/', views.TeamPoints, name='teamPoints'),
    path('login/', views.loginpage, name='login'),
    path('logout', views.logoutpage, name='logout'),
]

cricket_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cricket_application.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    {% block title %}
        <title>Home</title>
    {% endblock %}
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <style>
        .navbar a {
            color: white
        }

        body {
            background-image: url('../static/logos/wap.jpg');
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: 100% 100%;
        }

        h1, h2, h3, h4, h5, h6, td, th, label {
            color: white
        }
    </style>
</head>

{% include 'navbar.html' %}
<body>
{% if messages %}
    <div style="margin-top: 5%">
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                <p class="font-weight-bold">{{ message }}</p>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    </div>
{% endif %}
<div style="margin-top: 100px"></div>
{% block content %}

{% endblock %}
</body>
</html>

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top scrolling-navbar">
    <a class="navbar-brand" href="/"><img src="{% static 'logos/ipl logo.png' %}" width="50" height="50"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link navbar-brand" href="{% url 'cricket_application:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link navbar-brand" href="{% url 'cricket_application:schedule' %}">Schedule</a>
            </li>
            <li class="nav-item">
                <a class="nav-link navbar-brand" href="{% url 'cricket_application:team_list' %}">Teams</a>
            </li>
            <li class="nav-item">
                <a class="nav-link navbar-brand" href="{% url 'cricket_application:teamPoints' %}">Points</a>
            </li>
        </ul>
    </div>
</nav>